# Generated by Django 3.1 on 2023-01-11 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('unique_roll', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Unique Roll')),
                ('father_name', models.CharField(max_length=255, null=True, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=255, null=True, verbose_name="Mother's Name")),
                ('students_image', models.FileField(null=True, upload_to='Students_image/%Y/%m/%d/')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('present_address', models.TextField(max_length=255, null=True, verbose_name='Present Address')),
                ('permanent_address', models.TextField(max_length=255, null=True, verbose_name='Permanent Address')),
                ('personal_mobile_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0173456789)')], verbose_name='Personal Number')),
                ('gurdian_mobile_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0173456789)')], verbose_name='Gurdian Number')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admission Date')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=12, verbose_name='Gender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
