# Generated by Django 3.1 on 2023-01-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('exam_year', models.CharField(max_length=15, null=True, verbose_name='Exam Year')),
                ('date', models.DateField(null=True, verbose_name='Date of Exam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('exam_yea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.examyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_name', to='students.classname', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='students.exam', verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='result_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulta_info', to='students.resultinfo', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='students.subjects', verbose_name='Result Info'),
        ),
    ]
