# Generated by Django 3.1 on 2023-01-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20230112_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionClass',
            new_name='SectionClas',
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='result_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulta_info', to='students.resultinfo', verbose_name='Result Info'),
        ),
    ]
