# Generated by Django 3.1 on 2023-01-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20230112_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='students.subjects', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='section_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='students.sectionclas', verbose_name='Section'),
        ),
    ]
