# Generated by Django 3.2 on 2023-01-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20230116_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultinfo',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_name', to='students.classname', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='resultinfo',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='students.exam', verbose_name='Exam Type'),
        ),
        migrations.AddField(
            model_name='resultinfo',
            name='exam_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_years', to='students.examyear', verbose_name='Exam Year'),
        ),
        migrations.AddField(
            model_name='resultinfo',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_name', to='students.sectionclas', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='resultinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stnd', to='students.studentsinfo', verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='resultinfo',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_name', to='students.subjects', verbose_name='Subject'),
        ),
    ]
