# Generated by Django 3.2 on 2023-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20230120_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='code',
            field=models.CharField(max_length=255, null=True, verbose_name='Code'),
        ),
    ]
