# Generated by Django 4.1 on 2023-01-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_subjects_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='subjects',
        ),
        migrations.AddField(
            model_name='sectionclas',
            name='class_nm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cls_nm', to='students.classname', verbose_name='Class Name'),
        ),
    ]
