# Generated by Django 4.1 on 2023-01-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_classname_subjects_sectionclas_class_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='class_nm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clss_nme', to='students.classname', verbose_name='Class Names'),
        ),
    ]
