# Generated by Django 4.1 on 2023-01-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_subjects_class_nm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('class_year', models.CharField(max_length=15, null=True, verbose_name='Class Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classname',
            name='class_nm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cls_yr', to='students.classyear', verbose_name='Class Year'),
        ),
    ]
