# Generated by Django 4.1 on 2024-07-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_classyear_classname_class_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Blood Group Name'),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='relegion',
            field=models.CharField(choices=[('islam', 'Islam'), ('hindu', 'Hindu'), ('boudho', 'Boddho'), ('christan', 'Christan'), ('other', 'Other')], default='islam', max_length=12, verbose_name='Relegion'),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='session',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Session'),
        ),
    ]
