# Generated by Django 4.1 on 2024-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentsinfo_blood_group_studentsinfo_relegion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('display_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Order')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
