# Generated by Django 4.0.4 on 2022-08-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultural_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=3000)),
                ('photo_of_culturul_program', models.FileField(upload_to='culturul_program_Photo/')),
            ],
        ),
        migrations.CreateModel(
            name='DG_or_Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('photo', models.FileField(upload_to='Right_side_image_DG_or_chairman/')),
                ('texts', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gallery_photo', models.FileField(upload_to='Gallery_Photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Main_Page_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amader_dristi', models.TextField(max_length=500)),
                ('amader_lokkho', models.TextField(max_length=1000)),
                ('porichiti', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Montri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('photo', models.FileField(upload_to='Right_side_image_montri/')),
                ('texts', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News_headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=90)),
                ('img_or_pdf', models.FileField(blank=True, upload_to='News_headline/')),
                ('notice_published_date', models.DateField()),
                ('url_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=90)),
                ('img_or_pdf', models.FileField(blank=True, upload_to='Notice_board/')),
                ('notice_published_date', models.DateField()),
                ('url_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other_Employee_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Others_name', models.CharField(max_length=150)),
                ('about_Other', models.TextField(max_length=600)),
                ('Others_photo', models.FileField(upload_to='Other_Employee_Photo/')),
            ],
        ),
        migrations.CreateModel(
            name='SineBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('sineboard_photo', models.FileField(upload_to='Sine_board/')),
            ],
        ),
        migrations.CreateModel(
            name='Sochib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('photo', models.FileField(upload_to='Right_side_image_sochib/')),
                ('texts', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=3000)),
                ('photo_of_sports', models.FileField(upload_to='sports_Photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('fathers_name', models.CharField(max_length=150)),
                ('mothers_name', models.CharField(max_length=150)),
                ('unique_roll', models.IntegerField(unique=True)),
                ('mobile_number', models.IntegerField()),
                ('seasion', models.IntegerField()),
                ('class_name', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('short_address', models.TextField()),
                ('students_photo', models.FileField(blank=True, upload_to='Students_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(max_length=150)),
                ('about_teacher', models.TextField(max_length=600)),
                ('teachers_photo', models.FileField(upload_to='Teachers_Photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Upo_Montri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('photo', models.FileField(upload_to='Right_side_image_upomontri/')),
                ('texts', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Web_Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_headline', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=30)),
                ('institute_logo', models.FileField(upload_to='institute_logo/')),
            ],
        ),
    ]
