# Generated by Django 4.0.4 on 2022-08-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice_boards',
            new_name='Notice_board',
        ),
    ]
