# Generated by Django 4.0.4 on 2022-08-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0002_rename_notice_boards_notice_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matheti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.IntegerField()),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='news_headline',
            name='img_or_pdf',
            field=models.FileField(upload_to='News_headline/'),
        ),
        migrations.AlterField(
            model_name='students_information',
            name='blood_group',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='students_information',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students_information',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students_information',
            name='short_address',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='students_information',
            name='students_photo',
            field=models.FileField(default='d.jpg', upload_to='Students_photo/'),
        ),
    ]
