# Generated by Django 4.0.4 on 2022-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0009_alter_result_sub2_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_bn', models.CharField(max_length=50)),
                ('student_name_en', models.CharField(max_length=50)),
                ('student_father_name_bn', models.CharField(max_length=50)),
                ('student_father_name_en', models.CharField(max_length=50)),
                ('student_mother_name_bn', models.CharField(max_length=50)),
                ('student_mother_name_en', models.CharField(max_length=50)),
                ('gender_choise', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=80)),
                ('student_number', models.CharField(max_length=11)),
                ('gurdian_number', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
    ]
