# Generated by Django 4.0.4 on 2022-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0010_onlineadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadmission',
            name='online_admission_pic',
            field=models.FileField(default=1, upload_to='online_admission/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineadmission',
            name='gender_choise',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=80),
        ),
    ]
