# Generated by Django 4.0.4 on 2022-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0011_onlineadmission_online_admission_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=11)),
                ('address', models.TextField(blank=True, null=True)),
                ('complain_box', models.TextField()),
            ],
        ),
    ]
