# Generated by Django 4.0.4 on 2022-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0012_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
