# Generated by Django 4.0.4 on 2022-08-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0013_alter_complain_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
