# Generated by Django 4.0.4 on 2022-08-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0014_alter_complain_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_information',
            name='about_teacher',
        ),
        migrations.AddField(
            model_name='teachers_information',
            name='designation',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers_information',
            name='email',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers_information',
            name='phone_number',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
