# Generated by Django 4.0.4 on 2022-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0015_remove_teachers_information_about_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_information',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teachers_information',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
