# Generated by Django 4.0.4 on 2022-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0016_alter_teachers_information_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head_Teachers_speach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speach', models.TextField(max_length=2000)),
                ('picture', models.FileField(upload_to='online_admission/')),
            ],
        ),
    ]
