# Generated by Django 4.0.4 on 2022-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0017_head_teachers_speach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gallery_photo', models.FileField(upload_to='Heading_slider/')),
            ],
        ),
    ]
