# Generated by Django 4.0.4 on 2022-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0018_gallery_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leftside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amader_dristi', models.TextField()),
                ('amader_lokko', models.TextField()),
                ('short_porichiti', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lokko_uddessho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='other_employee_information',
            name='about_Other',
        ),
        migrations.AddField(
            model_name='head_teachers_speach',
            name='designation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='head_teachers_speach',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_employee_information',
            name='designation',
            field=models.CharField(default=64645, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_employee_information',
            name='email',
            field=models.EmailField(default=4, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_employee_information',
            name='phone_number',
            field=models.CharField(default=56465465, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='head_teachers_speach',
            name='speach',
            field=models.TextField(max_length=10000),
        ),
    ]
