# Generated by Django 4.0.4 on 2022-08-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0019_about_leftside_lokko_uddessho_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lokko_uddessho',
            old_name='details',
            new_name='lokko',
        ),
        migrations.RemoveField(
            model_name='lokko_uddessho',
            name='title',
        ),
        migrations.AddField(
            model_name='lokko_uddessho',
            name='uddesho',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students_information',
            name='religion',
            field=models.CharField(default='Muslim', max_length=50),
        ),
    ]
