# Generated by Django 4.0.4 on 2022-08-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0020_rename_details_lokko_uddessho_lokko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sineboard',
            name='url_link',
            field=models.URLField(blank=True),
        ),
    ]
