# Generated by Django 4.0.4 on 2022-08-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0021_sineboard_url_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_Page_Text',
        ),
    ]
