# Generated by Django 4.0.4 on 2022-08-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0022_delete_main_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_teachers_speach',
            name='picture',
            field=models.FileField(upload_to='Head_Teacherspeach/'),
        ),
        migrations.AlterField(
            model_name='students_information',
            name='students_photo',
            field=models.FileField(default='empty-profile.png', upload_to='Students_photo/'),
        ),
        migrations.AlterField(
            model_name='teachers_information',
            name='teachers_photo',
            field=models.FileField(default='empty-profile.png', upload_to='Teachers_Photo/'),
        ),
    ]
