# Generated by Django 4.1 on 2024-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0025_auto_20230116_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_heading',
            name='design_and_developer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
