# Generated by Django 4.1 on 2024-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0026_web_heading_design_and_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True)),
                ('icon', models.FileField(upload_to='important_link_logo/')),
            ],
        ),
    ]
