# Generated by Django 4.1 on 2024-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0027_importantlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadmission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
