# Generated by Django 4.1 on 2024-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_dashaboard', '0029_paymentgateway_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadmission',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Admission Fee'),
        ),
    ]
